version: '5.1.2'

services:
  web:
    build: ./apps/web
    ports:
      - "6666:6666"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  api:
    build: ./apps/api
    ports:
      - "5555:5555"
    volumes:
      - ./apps/api:/app
    env_file:
      - ./apps/api/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    env_file: ./apps/api/.env
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    volumes:
      - db_data:/var/lib/postgresql/data